sudo: required
language: generic

services:
  - docker

before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --debug --registry-mirror=https://mirror.gcr.io"'
  - sudo service docker restart
  - docker build -t slipmatsteve/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true slipmatsteve/react-test npm test

after_success:
  - docker build -t slipmatsteve/multi-client ./client
  - docker build -t slipmatsteve/multi-nginx ./nginx
  - docker build -t slipmatsteve/multi-server ./server
  - docker build -t slipmatsteve/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push slipmatsteve/multi-client
  - docker push slipmatsteve/multi-nginx
  - docker push slipmatsteve/multi-server
  - docker push slipmatsteve/multi-worker
